# Site settings
title: CodeCatz
email:
description: "coding study group"
baseurl: "codecatz.github.io"
url: "http://codecatz.github.io/"
ga_tracking_code: UA-
# Build settings

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

markdown: kramdown
#permalink: /:projects/:title

navigation:
    - title: About
      url: /about
    - title: Resources
      url: /resources
    - title: Tutorial
      url: /codecatz-tutorial

sass:
    sass_dir: _sass
    style: compressed


