# Site settings
title: CodeCatz
email:
description: "coding study group"
baseurl: ""
url: "http://codecatz.github.io/"

# Build settings
markdown: kramdown
permalink: /projects/:title.html

navigation:
    - title: About
      url: /about
    - title: Resources
      url: /resources
    - title: Tutorial
      url: /codecatz-tutorial

sass:
    sass_dir: _sass
    style: compressed


