# Site settings
title: CodeCatz
email:
description: "Girls Learning to Code"
baseurl: ""
url: "http://codecatz.github.io/"


# Build settings
markdown: kramdown
permalink: pretty


sass:
    sass_dir: _sass
    style: compressed


