# Site settings
title: CodeCatz
email:
description: "coding study group"
baseurl: ""
url: "http://codecatz.github.io/"

# Build settings
markdown: kramdown
permalink: /projects/:title.html

navigation:
    - title: About
      url: /about
    - title: Projects
      url: /projects
    - title: Join us
      url: /join-us

sass:
    sass_dir: _sass
    style: compressed


