# Site settings
title: "CodeCatz coding study group"
email:
description: "coding study group"
baseurl: ""
url: "http://codecatz.github.io/"
ga_tracking_code: UA-


# Build settings

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

markdown: kramdown
#permalink: /:projects/:title

navigation:
    - title: About
      url: /about
    - title: Resources
      url: /resources
    - title: Tutorial
      url: /codecatz-tutorial

sass:
    sass_dir: _sass
    style: compressed


# Content
description: "CodeCatz workshop is a one day workshop, where  we can teach you how to
 make your own website and host it on the internet. All you need is an idea
 and curiosity, we'll take care of the rest."



